### ISSUE TITLE
Crash when enabling Remote

### ISSUE THREAD

**Issue by Klick3R** [ORelio/Minecraft-Console-Client#104]
So this is what i get after a few seconds of running the client when having Remote enabled 

Unhandled Exception: System.ArgumentOutOfRangeException: Length cannot be less t
han zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at MinecraftClient.ChatBot.isPrivateMessage(String text, String& message, Str
ing& sender)
   at MinecraftClient.ChatBots.RemoteControl.GetText(String text)
   at MinecraftClient.McTcpClient.OnTextReceived(String text)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.handlePacket(Int32 pac
ketID, Byte[] packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Update()
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by ORelio** [comment]
This is caused by non standard chat format on your server. Latest dev build should fix this. If you wish to detect private messages you'll also have to specify chat format expression un configuration file ;)

**Comment by Klick3R** [comment]
Thank you for the quick reply, yes confirmed the latest dev build fixes the crash.
