### ISSUE TITLE
MinecraftClient.ini won't generate from MinecraftClient.exe

### ISSUE THREAD

**Issue by f2hafner** [ORelio/Minecraft-Console-Client#1141]
I cloned the repository from Github and moved everything into a different Folder named "MCC". Then I built the project with VS Code following the information provided in the README.md. After all that I ran "MinecraftClient.exe" in the bin folder and it gave me the following output in the console window of the client:

`Console Client for MC 1.4.6 to 1.16.1 - v1.16.1 - By ORelio & Contributors
Unhandled Exception: System.IO.FileNotFoundException: The file "C:\Users\thege\Documents\GitHub\MCC\MinecraftClient\bin\Release\MinecraftClient.ini" could not be found.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at MinecraftClient.Settings.WriteDefaultSettings(String settingsfile) in c:\Users\thege\Documents\GitHub\MCC\MinecraftClient\Settings.cs:Line 567.
   at MinecraftClient.Program.Main(String[] args) in c:\Users\thege\Documents\GitHub\MCC\MinecraftClient\Program.cs:Line 93.
(had to translate it because my systemlang is german)
`

After checking program.cs I found the following lines:

`
            else if (System.IO.File.Exists("MinecraftClient.ini"))
            {
                Settings.LoadSettings("MinecraftClient.ini");
            }
            else Settings.WriteDefaultSettings("MinecraftClient.ini");
`

shouldn't this just make a file with the default MinecraftClient.ini settings? (Using Windows 10)

**Comment by ORelio** [comment]
It is attempting to write the settings file but for some reason it cannot access the specified folder on your system:
https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Settings.cs#L567
`System.IO.File.WriteAllText(settingsfile, "<contents>", Encoding.UTF8);`

**Comment by f2hafner** [comment]
I noticed some weeks ago after a windows update, that some programs can't save files in my Github folder anymore, that's probably the reason why it got this error. I tried it on my Desktop and everything works fine. So this was an error on my side. Thank you for the quick reply and the great work you and all the other contributors put into this project. Consider this Closed.
