### ISSUE TITLE
Cant start MCC with Replaymod

### ISSUE THREAD

**Issue by Meowlan** [ORelio/Minecraft-Console-Client#1297]
**Prerequisites**
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [x] I have set `debugmessages=true` in config to diagnose my issue
 - [x] I have redacted session tokens and passwords before attaching screenshots

**Bug description**
So i installed MCC to afk at my Farm´s. I wanted to make an timelapse using Replay mod but if i try to start mcc with Replaymod it prints this to console
`Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at MinecraftClient.ChatBots.ReplayCapture.Initialize()
   at MinecraftClient.McClient.BotLoad(ChatBot b, Boolean init)
   at MinecraftClient.McClient.StartClient(String user, String uuid, String sessionID, String server_ip, UInt16 port, Int32 protocolversion, ForgeInfo forgeInfo, Boolean singlecommand, String command)
   at MinecraftClient.McClient..ctor(String username, String uuid, String sessionID, Int32 protocolversion, ForgeInfo forgeInfo, String server_ip, UInt16 port)
   at MinecraftClient.Program.InitializeClient()
   at MinecraftClient.Program.Main(String[] args)
`

**Comment by ReinforceZwei** [comment]
I found the problem and the issue will be fixed soon.

**Comment by Meowlan** [comment]
Thank you!

**Comment by ORelio** [comment]
The pull request containing the fix is now merged so you can grab the latest development build.
