### ISSUE TITLE
Silent quit

### ISSUE THREAD

**Issue by PhoenixGre** [ORelio/Minecraft-Console-Client#1390]
My client worked for quite a long time, great job on it! Recently though my client would randomly just quit, wouldnt send a reconnect message or anything, just up and disappear, so I logged on through command prompt to see the error message, and here's what I get:

Unhandled Exception: Ionic.Zlib.ZlibException: Bad state (unknown compression method (0x66))
   at Ionic.Zlib.InflateManager.Inflate(FlushType flush)
   at Ionic.Zlib.ZlibCodec.Inflate(FlushType flush)
   at Ionic.Zlib.ZlibBaseStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Ionic.Zlib.ZlibStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at MinecraftClient.Protocol.Handlers.ZlibUtils.Decompress(Byte[] to_decompress, Int32 size_uncompressed)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.ReadNextPacket(Int32& packetID, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Update()
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

I have no idea if this is a problem on my side or the client itself, but it happens quite often now, I'm only a first year studying software engineering, so I'm not very familiar with most of the things said in the error message and couldnt really find a solution cx

**Comment by ORelio** [comment]
Based on the stack trace, it seems related to packet compression. Packets sent between the server and the client might be compressed, a treshold is set when logging in and packets larger than that get compressed. Seems like a treshold is set in MCC by the server, but a packet received from the server is not valid Zlib compressed data. Not sure if it's a threshold issue, of if the data stream read from the server got out of sync and MCC tries to decompress the wrong part of the data. Would be hard to reproduce anyway 🤔

**Comment by PhoenixGre** [comment]
> Based on the stack trace, it seems related to packet compression. Packets sent between the server and the client might be compressed, a treshold is set when logging in and packets larger than that get compressed. Seems like a treshold is set in MCC by the server, but a packet received from the server is not valid Zlib compressed data. Not sure if it's a threshold issue, of if the data stream read from the server got out of sync and MCC tries to decompress the wrong part of the data. Would be hard to reproduce anyway 🤔

Basically what you're saying here is I have the equivalent of a rare genetic disorder? Just my luck ngl Cx

**Comment by ORelio** [comment]
Well, not exactly but it's indeed hard to diagnose because it happens after a long time x)

**Comment by PhoenixGre** [comment]
> Well, not exactly but it's indeed hard to diagnose because it happens after a long time x)

it happens quite often though, 3-30 minutes after opening the CC

**Comment by Vort** [comment]
Do your server supports offline mode? If so, I can log in and try to reproduce the problem.

**Comment by PhoenixGre** [comment]
> Do your server supports offline mode? If so, I can log in and try to reproduce the problem.

It does not unfortunately.
