### ISSUE TITLE
Unable to connect to 1.7.10 server

### ISSUE THREAD

**Issue by MCwenka** [ORelio/Minecraft-Console-Client#1419]
I tried to connect to a 1.7.10 server.
When I successfully connected to the server, the program crashed. 
It's the same server and game version as #1199 .But reporting errors is not the same.....

**Comment by MCwenka** [comment]
The IP address of this server is: yd.lcjm.club
These are the console outputs:

Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given
key was not present in the dictionary.
at System.Collections.Generic.Dictionary2.get_Item(TKey key) at MinecraftClient.Protocol.Handlers.PacketPalettes.PacketTypePalette.GetInco mmingTypeById(Int32 packetId) at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 pac ketID, Queue1 packetData)
at MinecraftClient.Protocol.Handlers.Protocol18Handler.Update()
at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater()
at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()

**Comment by ReinforceZwei** [comment]
I joined the server and MCC didn't crash. Are you using the latest version of MCC?

**Comment by Oopas** [comment]
> I joined the server and MCC didn't crash. Are you using the latest version of MCC?

I use the latest development build.
When I tried to run on Windows Server 2008 and windows 7, it gave me the same error report:
![-2217bf64e49d1355](https://user-images.githubusercontent.com/69417818/104834828-f3b97880-58dc-11eb-8ffb-40135183278e.jpg)

When I tried to run on Linux, it gave me the following error report:
![-4ceefc3283ffe13b](https://user-images.githubusercontent.com/69417818/104834852-34b18d00-58dd-11eb-9ce9-0d2b736560d9.jpg)

When I try to run it on Windows 10, it still crashes and fails to report errors(`Exception.ToString() fail`)

**Comment by ReinforceZwei** [comment]
Seems like server is sending some packet with ID `-26`, which is definitely weird. Normal ID range should be between `0` and `73`. Perhaps your server installed some new forge mods?

**Comment by MCwenka** [comment]
> Seems like server is sending some packet with ID `-26`, which is definitely weird. Normal ID range should be between `0` and `73`. Perhaps your server installed some new forge mods?

I've tried your revised version and it works very well.
This is a server with many mods.
Thanks for your help
