### ISSUE TITLE
Microsoft Account Failed to Login?

### ISSUE THREAD

**Issue by tunkusalim** [ORelio/Minecraft-Console-Client#1440]
i tried running the console client with repl.it, for mojang account its working fine, but when i tried using microsoft account it showing this error

```
~/ConsoleClient$ mono MinecraftClient.exe
Console Client for MC 1.4.6 to 1.16.5 - v1.16.5 - By ORelio & Contributors
AppVeyor build 444, built on Sun 01/31/2021 from commit d197648
﻿[MCC] [Settings] Loading Settings from /home/runner/ConsoleClient/MinecraftClient.ini
Resolving [Redacted]...
15:28:32 [MCC] [Translations] No translation file found for en. (Looked '/home/runner/ConsoleClient//lang/mcc/en.ini'
15:28:32 [MCC] [Translations] No translation file found for system language (en). (Looked '/home/runner/ConsoleClient//lang/mcc/en.ini'
15:28:32 Color test: Your terminal should display [0123456789ABCDEF]: [0123456789ABCDEF]
Connecting to Microsoft...
< GET /oauth20_authorize.srf?client_id=[Redacted]&redirect_uri=https://login.live.com/oauth20_desktop.srf&scope=service::user.auth.xboxlive.com::MBI_SSL&display=touch&response_type=token&locale=en HTTP/1.0
< Host: login.live.com
< User-Agent: Mozilla/5.0 (XboxReplay; XboxLiveAuth/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
< Accept: */*
< Connection: close
< 
< 
< POST /ppsecure/post.srf?client_id=[Redacted]&redirect_uri=https://login.live.com/oauth20_desktop.srf&scope=service::user.auth.xboxlive.com::MBI_SSL&display=touch&response_type=token&locale=en&contextid=[Redacted]&bk=[Redacted]&uaid=[Redacted]&pid=15216 HTTP/1.0
< Cookie: MSPRequ=id=N&lt=[Redacted]&co=1; uaid=[Redacted]; OParams=[Redacted]$; MSPOK=$uuid-[Redacted]
< Host: login.live.com
< User-Agent: Mozilla/5.0 (XboxReplay; XboxLiveAuth/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
< Accept: */*
< Connection: close
< Content-Type: application/x-www-form-urlencoded
< Content-Length: 317
< 
< login=[Redacted]&loginfmt=[Redacted]&passwd=[Redacted]&PPFT=[Redacted]
Status code: 204
Headers:

15:29:02 Microsoft authenticate failed: Unexpected response. Check your credentials. Response code: 204
15:29:02   at MinecraftClient.Protocol.XboxLive.UserLogin (System.String email, System.String password, MinecraftClient.Protocol.XboxLive+PreAuthResponse preAuth) [0x001ac] in <6d2e72d0b3114016858159b458f89795>:0 
  at MinecraftClient.Protocol.ProtocolHandler.MicrosoftLogin (System.String email, System.String password, MinecraftClient.Protocol.Session.SessionToken& session) [0x00044] in <6d2e72d0b3114016858159b458f89795>:0 
Minecraft Login failed :Incorrect password, blacklisted IP or too many logins.
15:29:02 [MCC] [AutoRelog] Launching with 2147483647 reconnection attempts
15:29:02 [MCC] [AutoRelog] Initializing without a kick message file
15:29:02 [MCC] [AutoRelog] Got disconnected with message: Minecraft Login failed :Incorrect password, blacklisted IP or too many logins.
15:29:02 [MCC] [AutoRelog] Ignoring kick message, reconnecting anyway.
15:29:02 [MCC] [AutoRelog] Waiting 60 seconds before reconnecting...
```
i dont know why its failed to login using microsoft account (i already change the .ini file with ``type=microsoft``)

**Comment by ReinforceZwei** [comment]
Sign in request should return 3XX redirect for success and 200 OK for fail. I am not sure what does 204 (No content) mean. Are you able to sign in on other platforms? (i.e. not repl.it)

**Comment by tunkusalim** [comment]
```Are you able to sign in on other platforms? (i.e. not repl.it)```
i havent tried with other platforms, but its working fine if im using mojang account

**Comment by tunkusalim** [comment]
if anyone know other platforms like repl.it,i tried heroku but idk how to run the script

**Comment by ORelio** [comment]
@ReinforceZwei With Mojang logins, HTTP responses were fully printed, this could help to print them too for Microsoft accounts.

**Comment by ReinforceZwei** [comment]
@ORelio I did implemented it to print out any available headers and cookies, also a bit of the body. What I mean here is seems like the response contains nothing.

> if anyone know other platforms like repl.it,i tried heroku but idk how to run the script

How about running MCC on your local machine? Does it work?

**Comment by tunkusalim** [comment]
``How about running MCC on your local machine? Does it work?``
it works fine on local machine

also i tried using proxy for login with the repl.it and it shows this error
```
Console Client for MC 1.4.6 to 1.16.5 - v1.16.5 - By ORelio & Contributors
AppVeyor build 444, built on Sun 01/31/2021 from commit d197648
﻿[MCC] [Settings] Loading Settings from /home/runner/ConsoleClient/MinecraftClient.ini
Resolving [Redacted]...
00:28:08 [MCC] [Translations] No translation file found for en. (Looked '/home/runner/ConsoleClient//lang/mcc/en.ini'
00:28:08 [MCC] [Translations] No translation file found for system language (en). (Looked '/home/runner/ConsoleClient//lang/mcc/en.ini'
00:28:08 Color test: Your terminal should display [0123456789ABCDEF]: [0123456789ABCDEF]
Connecting to Microsoft...
< GET /oauth20_authorize.srf?client_id=[Redacted]&redirect_uri=https://login.live.com/oauth20_desktop.srf&scope=service::user.auth.xboxlive.com::MBI_SSL&display=touch&response_type=token&locale=en HTTP/1.0
< Host: login.live.com
< User-Agent: Mozilla/5.0 (XboxReplay; XboxLiveAuth/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
< Accept: */*
< Connection: close
< 
< 
00:28:08 Connected to proxy [Redacted]:80
00:28:09 Microsoft authenticate failed: Fail to extract PPFT or urlPost
00:28:09   at MinecraftClient.Protocol.XboxLive.PreAuth () [0x0006e] in <6d2e72d0b3114016858159b458f89795>:0 
  at MinecraftClient.Protocol.ProtocolHandler.MicrosoftLogin (System.String email, System.String password, MinecraftClient.Protocol.Session.SessionToken& session) [0x0003b] in <6d2e72d0b3114016858159b458f89795>:0 
Minecraft Login failed :Incorrect password, blacklisted IP or too many logins.
00:28:09 [MCC] [AutoRelog] Launching with 2147483647 reconnection attempts
00:28:09 [MCC] [AutoRelog] Initializing without a kick message file
00:28:09 [MCC] [AutoRelog] Got disconnected with message: Minecraft Login failed :Incorrect password, blacklisted IP or too many logins.
00:28:09 [MCC] [AutoRelog] Ignoring kick message, reconnecting anyway.
00:28:09 [MCC] [AutoRelog] Waiting 60 seconds before reconnecting...
```
SOCKS5 protocol and Backbone Connection method settings from the proxy 
```
...
[Proxy]
enabled=login                      # Use 'false', 'true', or 'login' for login only
type=SOCKS5                          # Supported types: HTTP, SOCKS4, SOCKS4a, SOCKS5
server=[Redacted]:80                # Proxy server must allow HTTPS for login, and non-443 ports for playing
username=[Redacted]                          # Only required for password-protected proxies
password=[Redacted]                          # Only required for password-protected proxies
...
```

and when i tried the same thing on my local machine with the same proxy settings it also shows this error
```
AppVeyor build 437, built on Thu 01/07/2021 from commit 7cbf677
[MCC] [Settings] Loading Settings from C:\Users\maincraft\Desktop\MinecraftClient.ini
Resolving [Redacted]...
00:37:00 [MCC] [Translations] No translation file found for en. (Looked 'C:\Users\maincraft\Desktop\\lang\mcc\en.ini'
00:37:00 [MCC] [Translations] No translation file found for system language (en). (Looked 'C:\Users\maincraft\Desktop\\lang\mcc\en.ini'
00:37:00 Color test: Your terminal should display [0123456789ABCDEF]: [0123456789ABCDEF]
Connecting to Microsoft...
< GET /oauth20_authorize.srf?client_id=[Redacted]&redirect_uri=https://login.live.com/oauth20_desktop.srf&scope=service::user.auth.xboxlive.com::MBI_SSL&display=touch&response_type=token&locale=en HTTP/1.0
< Host: login.live.com
< User-Agent: Mozilla/5.0 (XboxReplay; XboxLiveAuth/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
< Accept: */*
< Connection: close
<
<
00:37:00 Connected to proxy [Redacted]:80
00:37:01 Microsoft authenticate failed: Fail to extract PPFT or urlPost
00:37:01    at MinecraftClient.Protocol.XboxLive.PreAuth()
   at MinecraftClient.Protocol.ProtocolHandler.MicrosoftLogin(String email, String password, SessionToken& session)
Minecraft Login failed :Incorrect password, blacklisted IP or too many logins.
00:37:01 [MCC] [AutoRelog] Launching with 2147483647 reconnection attempts
00:37:01 [MCC] [AutoRelog] Initializing without a kick message file
00:37:01 [MCC] [AutoRelog] Got disconnected with message: Minecraft Login failed :Incorrect password, blacklisted IP or too many logins.
00:37:01 [MCC] [AutoRelog] Ignoring kick message, reconnecting anyway.
00:37:01 [MCC] [AutoRelog] Waiting 60 seconds before reconnecting...
```

its working fine without proxy on my local machine

**Comment by ReinforceZwei** [comment]
Do local machine with proxy work?

**Comment by tunkusalim** [comment]
``Do local machine with proxy work?``
it works with mojang account, but not with the microsoft account

**Comment by ReinforceZwei** [comment]
Could you have your machine with proxy enabled and open the following link in the web browser?

`https://login.live.com/oauth20_authorize.srf?client_id=000000004C12AE6F&redirect_uri=https://login.live.com/oauth20_desktop.srf&scope=service::user.auth.xboxlive.com::MBI_SSL&display=touch&response_type=token&locale=en`

You will see the Microsoft account sign in page if everything works fine.

**Comment by tunkusalim** [comment]
```
Could you have your machine with proxy enabled and open the following link in the web browser?

https://login.live.com/oauth20_authorize.srf?client_id=000000004C12AE6F&redirect_uri=https://login.live.com/oauth20_desktop.srf&scope=service::user.auth.xboxlive.com::MBI_SSL&display=touch&response_type=token&locale=en

You will see the Microsoft account sign in page if everything works fine.
```
its says "Too Many Requests", is mean my proxy is blocked or something?

**Comment by ReinforceZwei** [comment]
> is it mean my proxy is blocked or something

I guess yes.

**Comment by ReinforceZwei** [comment]
Maybe it is the same case for repl.it, IP being blacklisted by Microsoft.

**Comment by tunkusalim** [comment]
so, uhh i got new proxy and now im able to open this link on my browser, which means its not blacklisted by microsoft right? 

> Could you have your machine with proxy enabled and open the following link in the web browser?
> 
> `https://login.live.com/oauth20_authorize.srf?client_id=000000004C12AE6F&redirect_uri=https://login.live.com/oauth20_desktop.srf&scope=service::user.auth.xboxlive.com::MBI_SSL&display=touch&response_type=token&locale=en`
> 
> You will see the Microsoft account sign in page if everything works fine.

but then it shows this error
```
Console Client for MC 1.4.6 to 1.16.5 - v1.16.5 - By ORelio & Contributors
AppVeyor build 444, built on Sun 01/31/2021 from commit d197648
﻿[MCC] [Settings] Loading Settings from /home/runner/ConsoleClient/MinecraftClient.ini
Resolving survival.manacube.net...
10:34:33 [MCC] [Translations] No translation file found for en. (Looked '/home/runner/ConsoleClient//lang/mcc/en.ini'
10:34:33 [MCC] [Translations] No translation file found for system language (en). (Looked '/home/runner/ConsoleClient//lang/mcc/en.ini'
10:34:33 Color test: Your terminal should display [0123456789ABCDEF]: [0123456789ABCDEF]
Connecting to Microsoft...
< GET /oauth20_authorize.srf?client_id=[Redacted]&redirect_uri=https://login.live.com/oauth20_desktop.srf&scope=service::user.auth.xboxlive.com::MBI_SSL&display=touch&response_type=token&locale=en HTTP/1.0
< Host: login.live.com
< User-Agent: Mozilla/5.0 (XboxReplay; XboxLiveAuth/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
< Accept: */*
< Connection: close
< 
< 
10:34:33 Connected to proxy 45.154.244.149:8187
< POST /ppsecure/post.srf?client_id=[Redacted]&redirect_uri=https://login.live.com/oauth20_desktop.srf&scope=service::user.auth.xboxlive.com::MBI_SSL&display=touch&response_type=token&locale=en&contextid=[Redacted]&bk=[Redacted]&uaid=[Redacted]&pid=15216 HTTP/1.0
< Cookie: MSPRequ=id=N&lt=1612175675&co=1; uaid=[Redacted]; OParams=[Redacted]$; MSPOK=$uuid-[Redacted]
< Host: login.live.com
< User-Agent: Mozilla/5.0 (XboxReplay; XboxLiveAuth/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
< Accept: */*
< Connection: close
< Content-Type: application/x-www-form-urlencoded
< Content-Length: 325
< 
< login=[Redacted]&loginfmt=[Redacted]&passwd=[Redacted]&PPFT=[Redacted]
Status code: 200
Headers:
  cache-control: no-store, no-cache
  pragma: no-cache
  content-length: 1479
  content-type: text/html; charset=utf-8
  expires: Mon, 01 Feb 2021 10:33:36 GMT
  p3p: CP="DSP CUR OTPi IND OTRi ONL FIN"
  referrer-policy: strict-origin-when-cross-origin
  x-ms-request-id: d7d7ea5f-5ccb-4c11-8916-8bcaa3628755
  ppserver: PPV: 30 H: BY1PEPF00001E6F V: 0
  x-content-type-options: nosniff
  strict-transport-security: max-age=31536000
  x-xss-protection: 1; mode=block
  date: Mon, 01 Feb 2021 10:34:36 GMT
  connection: close

Cookies: 
  MSPOK=
  PPAuth=-[Redacted]
  PPLState=1
  MSPShared=
  MSPPre=[Redacted]|[Redacted]||
  MSPCID=[Redacted]
  pres=
  LOpt=1
  MSPVis=$38936
  OParams=[Redacted]$
  MSPBack=1612175675

Body: (Truncated to 200 characters)
<html><head><noscript>JavaScript required to sign in<meta http-equiv="Refresh" content="0; URL=https://login.live.com/jsDisabled.srf?mkt=EN-US&lc=1033&uaid=[Redacted]"/></noscrip...

10:34:36 Microsoft authenticate failed: Unexpected response. Check your credentials. Response code: 200
10:34:36   at MinecraftClient.Protocol.XboxLive.UserLogin (System.String email, System.String password, MinecraftClient.Protocol.XboxLive+PreAuthResponse preAuth) [0x001ac] in <6d2e72d0b3114016858159b458f89795>:0 
  at MinecraftClient.Protocol.ProtocolHandler.MicrosoftLogin (System.String email, System.String password, MinecraftClient.Protocol.Session.SessionToken& session) [0x00044] in <6d2e72d0b3114016858159b458f89795>:0 
Minecraft Login failed :Incorrect password, blacklisted IP or too many logins.
10:34:36 [MCC] [AutoRelog] Launching with 2147483647 reconnection attempts
10:34:36 [MCC] [AutoRelog] Initializing without a kick message file
10:34:36 [MCC] [AutoRelog] Got disconnected with message: Minecraft Login failed :Incorrect password, blacklisted IP or too many logins.
10:34:36 [MCC] [AutoRelog] Ignoring kick message, reconnecting anyway.
10:34:36 [MCC] [AutoRelog] Waiting 60 seconds before reconnecting..
```

**Comment by ReinforceZwei** [comment]
Code 200 mean there's something wrong while signing in. It could be wrong password, 2FA enabled, etc. I would suggest you to sign in with your new proxy in your browser. If success, a blank white page will be appear. The access token is inside the URL above.

**Comment by tunkusalim** [comment]
oh right, i signin using that respond url with same proxy and now everything working fine
```
Body: (Truncated to 200 characters)
<html><head><noscript>JavaScript required to sign in<meta http-equiv="Refresh" content="0; URL=https://login.live.com/jsDisabled.srf?mkt=EN-US&lc=1033&uaid=[Redacted]"/></noscrip...
```

final response
```
Console Client for MC 1.4.6 to 1.16.5 - v1.16.5 - By ORelio & Contributors
AppVeyor build 444, built on Sun 01/31/2021 from commit d197648
﻿[MCC] [Settings] Loading Settings from /home/runner/ConsoleClient3/MinecraftClient.ini
Resolving [Redacted]...
10:48:50 [MCC] [Translations] No translation file found for en. (Looked '/home/runner/ConsoleClient3//lang/mcc/en.ini'
10:48:50 [MCC] [Translations] No translation file found for system language (en). (Looked '/home/runner/ConsoleClient3//lang/mcc/en.ini'
10:48:50 Color test: Your terminal should display [0123456789ABCDEF]: [0123456789ABCDEF]
Connecting to Microsoft...
< GET /oauth20_authorize.srf?client_id=[Redacted]&redirect_uri=https://login.live.com/oauth20_desktop.srf&scope=service::user.auth.xboxlive.com::MBI_SSL&display=touch&response_type=token&locale=en HTTP/1.0
< Host: login.live.com
< User-Agent: Mozilla/5.0 (XboxReplay; XboxLiveAuth/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
< Accept: */*
< Connection: close
< 
< 
10:48:50 Connected to proxy [Redacted]:[Redacted]
< POST /ppsecure/post.srf?client_id=[Redacted]&redirect_uri=https://login.live.com/oauth20_desktop.srf&scope=service::user.auth.xboxlive.com::MBI_SSL&display=touch&response_type=token&locale=en&contextid=[Redacted]&bk=[Redacted]&uaid=[Redacted]&pid=15216 HTTP/1.0
< Cookie: MSPRequ=id=N&lt=1612176531&co=1; uaid=[Redacted]; OParams=[Redacted]$; MSPOK=$uuid-[Redacted]
< Host: login.live.com
< User-Agent: Mozilla/5.0 (XboxReplay; XboxLiveAuth/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
< Accept: */*
< Connection: close
< Content-Type: application/x-www-form-urlencoded
< Content-Length: 329
< 
< login=[Redacted]&loginfmt=[Redacted]&passwd=[Redacted]&PPFT=[Redacted]
Status code: 302
Headers:
  cache-control: no-store, no-cache
  pragma: no-cache
  content-length: 0
  content-type: text/html; charset=utf-8
  expires: Mon, 01 Feb 2021 10:47:52 GMT
  location: https://login.live.com/oauth20_desktop.srf?lc=1033#access_token=[Redacted]&token_type=bearer&expires_in=86400&scope=service::user.auth.xboxlive.com::MBI_SSL&refresh_token=[Redacted]&user_id=[Redacted]
  p3p: CP="DSP CUR OTPi IND OTRi ONL FIN"
  referrer-policy: strict-origin-when-cross-origin
  x-ms-request-id: 9b24cbc6-f91d-4a1a-b9f7-0e2e4a4bbde4
  ppserver: PPV: 30 H: BY1PPF3C4BF9011 V: 0
  x-content-type-options: nosniff
  strict-transport-security: max-age=31536000
  x-xss-protection: 1; mode=block
  date: Mon, 01 Feb 2021 10:48:52 GMT
  connection: close

Cookies: 
  MSPOK=
  PPAuth=-[Redacted]$$
  PPLState=1
  MSPShared=
  MSPPre=[Redacted]|[Redacted]||
  MSPCID=c2e785032e69721d
  MSPAuth=[Redacted]$$
  MSPProf=[Redacted]
  NAP=V=1.9&E=18bb&C=fABy0N42OaY0OntsMp9Ds8&W=1
  ANON=A=027A7CEF&E=1915&W=1
  pres=
  LOpt=1
  WLSSC=[Redacted]==
  JSH=2$[Redacted]$$

< GET /oauth20_desktop.srf?lc=1033 HTTP/1.0
< Host: login.live.com
< User-Agent: MCC/1.16.5
< Accept: */*
< Connection: close
< 
< 
< POST /user/authenticate HTTP/1.0
< Host: user.auth.xboxlive.com
< User-Agent: Mozilla/5.0 (XboxReplay; XboxLiveAuth/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
< Accept: application/json
< Connection: close
< x-xbl-contract-version: 0
< Content-Type: application/json
< Content-Length: 1168
< 
< {"Properties": {"AuthMethod": "RPS","SiteName": "user.auth.xboxlive.com","RpsTicket": "[Redacted]=="},"RelyingParty": "http://auth.xboxlive.com","TokenType": "JWT"}
Status code: 200
Headers:
  cache-control: no-cache, no-store
  keep-alive: true
  content-length: 1640
  content-type: application/json
  ms-cv: bWPTigj6rEe6cUhBUcD/Ig.0
  x-content-type-options: nosniff
  x-xblcorrelationid: 00000000-0000-0000-0000-000000000000
  x-err: 00000005
  date: Mon, 01 Feb 2021 10:48:55 GMT
  connection: close

Body: (Truncated to 200 characters)
{"IssueInstant":"2021-02-01T10:48:55.4239421Z","NotAfter":"2021-02-15T10:48:55.4239421Z","Token":"[Redacted]...

< POST /xsts/authorize HTTP/1.0
< Host: xsts.auth.xboxlive.com
< User-Agent: Mozilla/5.0 (XboxReplay; XboxLiveAuth/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
< Accept: application/json
< Connection: close
< x-xbl-contract-version: 1
< Content-Type: application/json
< Content-Length: 1611
< 
< {"Properties": {"SandboxId": "RETAIL","UserTokens": ["[Redacted]"]},"RelyingParty": "rp://api.minecraftservices.com/","TokenType": "JWT"}
Status code: 200
Headers:
  cache-control: no-cache, no-store
  keep-alive: true
  content-length: 2259
  content-type: application/json
  ms-cv: TWyJazNdq0m9cWrJHSg2sw.0
  x-content-type-options: nosniff
  x-xblcorrelationid: d5e9455d-56f0-4ed1-8d8e-5775e7dd644a
  date: Mon, 01 Feb 2021 10:48:56 GMT
  connection: close

Body: (Truncated to 200 characters)
{"IssueInstant":"2021-02-01T10:48:56.8865658Z","NotAfter":"2021-02-02T02:48:56.8865658Z","Token":"[Redacted]...

< POST /authentication/login_with_xbox HTTP/1.0
< Host: api.minecraftservices.com
< User-Agent: MCC/1.16.5
< Accept: application/json
< Connection: close
< Content-Type: application/json
< Content-Length: 2153
< 
< {"identityToken": "XBL3.0 x=[Redacted]"}
Status code: 200
Headers:
  date: Mon, 01 Feb 2021 10:48:58 GMT
  content-type: application/json
  content-length: 479
  connection: close
  x-minecraft-request-id: [Redacted]
  cache-control: no-store

Body: (Truncated to 200 characters)
{
  "username" : "[Redacted]",
  "roles" : [ ],
  "access_token" : "[Redacted]...

< GET /entitlements/mcstore HTTP/1.0
< Host: api.minecraftservices.com
< User-Agent: MCC/1.16.5
< Accept: */*
< Connection: close
< Authorization: Bearer [Redacted]
< 
< 
Status code: 200
Headers:
  date: Mon, 01 Feb 2021 10:48:59 GMT
  content-type: application/json
  content-length: 2744
  connection: close
  x-minecraft-request-id: c3b73f74c8fd9cb3
  cache-control: no-store

Body: (Truncated to 200 characters)
{
  "items" : [ {
    "name" : "product_minecraft",
    "signature" : "[Redacted]...

< GET /minecraft/profile HTTP/1.0
< Host: api.minecraftservices.com
< User-Agent: MCC/1.16.5
< Accept: */*
< Connection: close
< Authorization: Bearer [Redacted]
< 
< 
Status code: 200
Headers:
  date: Mon, 01 Feb 2021 10:49:00 GMT
  content-type: application/json
  content-length: 324
  connection: close
  x-minecraft-request-id: 9d2458747036fd8f
  cache-control: no-store

Body: (Truncated to 200 characters)
{
  "id" : "[Redacted]",
  "name" : "[Redacted]",
  "skins" : [ {
    "id" : "[Redacted]",
    "state" : "ACTIVE",
    "url" : "http://textures.minecraft.ne...

Success. (session ID: [Redacted])
10:49:00 Using Minecraft version 1.15.2 (protocol v578)
Checking if server is running Forge...
```

**Comment by ReinforceZwei** [comment]
So what's the problem... It just suddenly work after you opened some URL in your browser with the proxy?

**Comment by tunkusalim** [comment]
i think its because
1. Repl.it ip was blocked/blacklisted by microsoft
2. My proxy ip also blocked/blacklisted
3. 2FA Authentication with the microsoft account?

**Comment by ReinforceZwei** [comment]
2FA is not supported at the moment and will definitely not work. MCC will ask you to disable 2FA if it is the case. So I think IP being blacklisted would be the explanation.
