### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by PhoenixGre** [ORelio/Minecraft-Console-Client#1483]
My clients keep crashing, crashing so much that RestartOnCrash is giving up on them, how do I fix this?
Unhandled Exception:
>Ionic.Zlib.ZlibException: Bad state (unknown compression method (0x35))
   at Ionic.Zlib.InflateManager.Inflate(FlushType flush)
   at Ionic.Zlib.ZlibCodec.Inflate(FlushType flush)
   at Ionic.Zlib.ZlibBaseStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Ionic.Zlib.ZlibStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at MinecraftClient.Protocol.Handlers.ZlibUtils.Decompress(Byte[] to_decompress, Int32 size_uncompressed)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.ReadNextPacket(Int32& packetID, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Update()
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by ReinforceZwei** [comment]
Are you using the latest version? Could you provide the server address so that I can try to reproduce the crash?

**Comment by ORelio** [comment]
I think this error happens if the client somehow gets out of sync with the server and tries to decompress garbage data. Even if we don't find the root cause, we could catch this exception in OnUpdate() and handle this as a connection lost:
https://github.com/ORelio/Minecraft-Console-Client/blob/b78e8e064aecdbf04882f97325dbde77081dc5e3/MinecraftClient/Protocol/Handlers/Protocol18.cs#L178-L197

**Comment by PhoenixGre** [comment]
I lost access to my account for a while, it was a problem with my internet, I changed my internet coop and now it works almost perfectly

**Comment by ORelio** [comment]
OK, I think this error happens because the compressed data is truncated... so it really was connection lost after all.
