### ISSUE TITLE
Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by tunkusalim** [ORelio/Minecraft-Console-Client#1552]
I got error response when i enabled forced HTTPS on my site, and when i turned off the forced HTTPS its working fine again
```
07:42:47 [MCC] [Script] script script.cs
07:41:47 [MCC] [Script] Script 'script.cs' failed to run (RuntimeError).
07:41:47 [MCC] [Script] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.GetResponse()
   at ScriptLoader.Script.__run(CSharpAPI __apiHandler, String[] args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at MinecraftClient.CSharpRunner.Run(ChatBot apiHandler, ManualResetEvent tickHandler, String[] lines, String[] args, Dictionary`2 localVars, Boolean run)
```

my ``script.cs``
```
//MCCScript 1.0

DateTime now = DateTime.Now;
var dataURL = "http://xxx.xxx/xxx.php?beacon=alive";

var request = (System.Net.HttpWebRequest)System.Net.WebRequest.Create(dataURL);
    request.ContentType = "application/x-www-form-urlencoded";
    request.Method = "POST";
    var response = (System.Net.HttpWebResponse)request.GetResponse();
    string responseString;
    using (var stream = response.GetResponseStream())
        using (var reader = new StreamReader(stream))
            responseString = reader.ReadToEnd();
MCC.LogToConsole(responseString);

//MCCScript Extensions

```
same thing happens when i change ``dataURL`` to https ``https://xxx.xxx/xxx.php?beacon=alive``

how can i fix this?

**Comment by tunkusalim** [comment]
```
Console Client for MC 1.4.6 to 1.16.5 - v1.16.5 - By ORelio & Contributors
AppVeyor build 470, built on Sun 04/18/2021 from commit 663d617
```

**Comment by ReinforceZwei** [comment]
It sounds like there's a mis-configuration of your site. Are you able to visit your site using regular browser?

**Comment by tunkusalim** [comment]
> It sounds like there's a mis-configuration of your site. Are you able to visit your site using regular browser?

its working fine on [my browser](https://prnt.sc/11zd9ao), but i see that running curl with cmd also showing ``Could not create SSL/TLS secure channel``.

the solution i find is adding this to the script
```
ServicePointManager.Expect100Continue = true;
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
```

...
```c#
//MCCScript 1.0

ServicePointManager.Expect100Continue = true;
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
DateTime now = DateTime.Now;
var dataURL = "https://xxx.xxx/xxx.php?beacon=alive";

var request = (System.Net.HttpWebRequest)System.Net.WebRequest.Create(dataURL);
    request.ContentType = "application/x-www-form-urlencoded";
    request.Method = "POST";
    var response = (System.Net.HttpWebResponse)request.GetResponse();
    string responseString;
    using (var stream = response.GetResponseStream())
        using (var reader = new StreamReader(stream))
            responseString = reader.ReadToEnd();
MCC.LogToConsole(responseString);

//MCCScript Extensions

```
 now its working with https
