### ISSUE TITLE
play.heavenmc.co

### ISSUE THREAD

**Issue by railroadss** [ORelio/Minecraft-Console-Client#1553]
System.IO.InvalidDataException: Failed to process incoming packet of type ChatMessage. (PacketID: 2, Protocol: 47, LoginPhase: False, InnerException: System.InvalidOperationException). ---> System.InvalidOperationException: Queue empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Queue`1.Dequeue()
   at MinecraftClient.Protocol.Handlers.DataTypes.ReadData(Int32 offset, Queue`1 cache)
   at MinecraftClient.Protocol.Handlers.DataTypes.ReadNextString(Queue`1 cache)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   --- End of inner exception stack trace ---
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Update()
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by ReinforceZwei** [comment]
What is the version of this server?

**Comment by ORelio** [comment]
Protocol 47 should be 1.8.x

**Comment by ReinforceZwei** [comment]
I am not able to join this server. Server ping is working and reported it's version.
```
Server version : Travertine 1.7.x, 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x (protocol v736)
```

But client stuck at `Checking Session...`.

**Comment by ORelio** [comment]
This issue might be related to #1519 where the client is stuck at login because MCC does not time out at login 🤔

**Comment by ReinforceZwei** [comment]
I tried to log the packet out and I saw some weird packet IDs. _(Please ignore the packet type as they are incorrect)_
```
[MCC] Version is supported.                                                             
Logging in...                                                                           
<<< 0x00 - TeleportConfirm                                                              
<<< 0x00 - TeleportConfirm                                                              
>>> 0x01 - SpawnExperienceOrb                                                           
[MCC] Checking Session...                                                               
<<< 0x01 - QueryBlockNBT                                                                
>>> 0x03 - SpawnPainting                                                                
>>> 0x20 - KeepAlive                                                                    
>>> 0x3B - EntityHeadLook                                                               
[ERROR] OnNetworkPacket: Got error from MinecraftClient.ChatBots.PacketDump: System.Collections.Generic.KeyNotFoundException: Packet ID of 0x2C3 doesn't exist!
```

I also tried to use vanilla client with debug proxy and hoping to see the packet IDs but the server rejected me
![image](https://user-images.githubusercontent.com/39955851/116549311-e4a88480-a927-11eb-89a2-ea2f483c6501.png)

So I am going to leave this issue here until having more information.

**Comment by ORelio** [comment]
Seems like the server address in https://wiki.vg/Protocol#Handshake is not the one expected by the server.
Maybe you could edit the proxy to force the one expected by the server.

**Comment by ORelio** [comment]
We could not reproduce. Feel free to reopen if you have more info about this bug report.
