### ISSUE TITLE
Force server resourcepack

### ISSUE THREAD

**Issue by Rabkaleta** [ORelio/Minecraft-Console-Client#1649]
Unhandled Exception: System.IO.InvalidDataException: Failed to process incoming packet of type ResourcePackSend. (PacketID: 56, Protocol: 754, LoginPhase: False, InnerException: System.InvalidOperationException). ---> System.InvalidOperationException: Queue empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Queue`1.Dequeue()
   at MinecraftClient.Protocol.Handlers.DataTypes.ReadNextBool(Queue`1 cache)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   --- End of inner exception stack trace ---
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Update()
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
   
help me pls

**Comment by ReinforceZwei** [comment]
This issue have been fixed. See #1637.  Please download the latest version from [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).
