### ISSUE TITLE
Modded forge server join, Index out of range error.

### ISSUE THREAD

**Issue by ZizzyDizzyMC** [ORelio/Minecraft-Console-Client#165]
I am trying to connect to a heavily modded server with over 180 mods.  I assume something is amiss with a packet but I can't figure out what. The account actually connected but didn't stay on for long after this error.  I'm not a good enough coder to figure it out so I'm leaving the error here for others.

```
Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.readNextByte(List`1 cache)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.readNextBool(List`1 cache)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.handlePacket(Int32 packetID, List`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Update()
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by ORelio** [comment]
Just according to the stack trace, it seems like the Forge handler was expecting more data in the plugin message than there actually was, and thus crashed. Enabling debug in INI file and showing the whole connection log could help.

**Comment by ZizzyDizzyMC** [comment]
```
Console Client for MC 1.4.6 to 1.10.0 - v1.10.0 DEV - By ORelio & Contributors
Connecting to Minecraft.net...
Success. (session ID: REDACTED)
Retrieving Server Info...
Server is running Forge. Mod list:
  mcp v9.05
  FML v7.10.99.99
  Forge v10.13.4.1614
  appliedenergistics2-core vrv3-beta-5
  CodeChickenCore v1.0.7.47
  NotEnoughItems v1.0.5.118
  OpenComputers|Core v1.6.0.3-rc.1
  ThE-core v0.10.0.0
  ThaumicTinkerer-preloader v0.1
  ChocoPatcher v1.1
  OpenModsCore v0.9.1
  <CoFH ASM> v000
  BinniePatcher v1.7.1
  FastCraft v1.23
  IC2 v2.2.819-experimental
  AdvancedSolarPanel v1.7.10-3.5.1
  AgriCraft v1.7.10-1.5.0
  appliedenergistics2 vrv3-beta-5
  AWWayofTime vv1.3.3
  Baubles v1.0.1.10
  Thaumcraft v4.2.3.5
  Botania vr1.8-249
  Avaritia v1.11
  bdlib v1.9.4.109
  betterrecords v@VERSION@
  BiblioCraft v1.11.4
  BiblioWoodsBoP v1.9
  CoFHCore v1.7.10R3.1.2
  Forestry v4.2.11.59
  BiblioWoodsForestry v1.7
  BiblioWoodsNatura v1.5
  ThermalFoundation v1.7.10R1.2.3
  ThermalExpansion v1.7.10R4.1.2
  BigReactors v0.4.3A
  BinnieCore v2.0-pre14
  Botany v2.0-pre14
  ExtraBees v2.0-pre14
  ExtraTrees v2.0-pre14
  Genetics v2.0-pre14
  BiomeTweaker v2.0.182
  BrandonsCore v1.0.0.12
  BuildCraft|Core v7.1.16
  BuildCraft|Builders v7.1.16
  BuildCraft|Transport v7.1.16
  BuildCraft|Energy v7.1.16
  BuildCraft|Silicon v7.1.16
  BuildCraft|Robotics v7.1.16
  BuildCraft|Factory v7.1.16
  BuildCraft|Compat v7.1.3
  CarpentersBlocks v3.3.7
  catwalks v2.0.4
  catwalkmod vx.x.x
  Railcraft v9.10.0.0
  ForgeMultipart v1.2.0.345
  chisel v2.9.5.11
  ComputerCraft v1.75
  cookingbook v1.0.134
  customnpcs v1.7.10d
  endercore v1.7.10-0.2.0.34_beta
  customthings vMC1.7.10-0.0.3-49
  PTRModelLib v1.0.0
  props v2.3.0
  DraconicEvolution v1.0.2a
  emobile v1.2.1
  MineFactoryReloaded v1.7.10R2.8.1
  Waila v1.5.10
  EnderIO v1.7.10-2.3.0.424_beta
  EnderStorage v1.4.7.37
  EnderTech v1.7.10-0.3.2.405
  exnihilo v1.38-49
  RedstoneArsenal v1.7.10R1.1.2
  ExtraUtilities v1.2.12
  ImmersiveEngineering v0.7.5
  Mantle v1.7.10-0.3.2.jenkins191
  TConstruct v1.7.10-1.8.8.build988
  exastris vMC1.7.10-1.16-36
  excompressum v1.0
  extracells v2.3.9
  fastleafdecay v1.4
  ThaumicTinkerer vunspecified
  ForbiddenMagic v1.7.10-0.574
  forgeanalytics v0.0.0.16
  FTBI v1.1.1
  MineTweaker3 v3.0.10
  FTBL v1.0.18.2
  ftbtrophies v1.0.7
  funkylocomotion v1.0
  MagicBees v2.4.3
  gendustry v1.6.3.132
  GraviSuite v1.7.10-2.0.3
  guideapi v1.7.10-1.0.1-20
  IC2NuclearControl v2.3.4a
  immersiveintegration v0.6.8
  inpure|core v1.7.10R1.0.0B9
  IronChest v6.0.62.742
  ivansupport v1.0.0
  JABBA v1.2.1
  kleeslabs v1.0
  LogisticsPipes v0.9.3.122
  MineFactoryReloaded|CompatAppliedEnergistics v1.7.10R2.8.1
  MineFactoryReloaded|CompatBuildCraft v1.7.10R2.8.1
  MineFactoryReloaded|CompatForestry v1.7.10R2.8.1
  MineFactoryReloaded|CompatForgeMicroblock v1.7.10R2.8.1
  MineFactoryReloaded|CompatIC2 v1.7.10R2.8.1
  MrTJPCoreMod v1.1.0.33
  ProjRed|Core v4.7.0pre12.95
  ProjRed|Exploration v4.7.0pre12.95
  MineFactoryReloaded|CompatProjRed v1.7.10R2.8.1
  MineFactoryReloaded|CompatRailcraft v1.7.10R2.8.1
  MineFactoryReloaded|CompatThaumcraft v1.7.10R2.8.1
  MineFactoryReloaded|CompatThermalExpansion v1.7.10R2.8.1
  MineFactoryReloaded|CompatTConstruct v1.7.10R2.8.1
  MineFactoryReloaded|CompatVanilla v1.7.10R2.8.1
  modtweaker2 v0.9.5
  Morpheus v1.7.10-1.6.21
  NEIAddons v1.12.14.40
  NEIAddons|Developer v1.12.14.40
  NEIAddons|AppEng v1.12.14.40
  NEIAddons|Botany v1.12.14.40
  NEIAddons|Forestry v1.12.14.40
  NEIAddons|CraftingTables v1.12.14.40
  NEIAddons|ExNihilo v1.12.14.40
  neiintegration v1.1.2
  OpenMods v0.9.1
  OpenBlocks v1.5.1
  ProjRed|Transmission v4.7.0pre12.95
  OpenComputers v1.6.0.3-rc.1
  openfm v0.1.0.34
  openglasses v1.0.46
  OpenPeripheralCore v1.3
  OpenPeripheral v0.5.1
  OpenPeripheralIntegration v0.5
  harvestcraft v1.7.10j
  playblock v1.3.2
  worldedit v6.1.1-SNAPSHOT
  plume v1.0.0
  ProjRed|Transportation v4.7.0pre12.95
  ProjRed|Compatibility v4.7.0pre12.95
  ProjRed|Integration v4.7.0pre12.95
  ProjRed|Illumination v4.7.0pre12.95
  ProjRed|Expansion v4.7.0pre12.95
  rftools v4.23
  simplyjetpacks v1.5.3
  skcraftshenanigans v1.3.1
  SolarExpansion v1.6a
  StevesCarts v2.0.0.b18
  StorageDrawers v1.7.10-1.9.7
  StorageDrawersBop v1.7.10-1.1.1
  StorageDrawersForestry v1.7.10-1.1.2
  StorageDrawersMisc v1.7.10-1.1.2
  StorageDrawersNatura v1.7.10-1.1.1
  tcinventoryscan v1.0.11
  thaumcraftneiplugin v@VERSION@
  thaumicenergistics v1.0.0.1
  ThaumicExploration v0.6.0
  ThermalDynamics v1.7.10R1.1.0
  TiCTooltips v1.2.5
  TMechworks v0.2.15.106
  WailaHarvestability v1.1.6
  wawla v1.3.3
  witchery v0.24.1
  WR-CBE|Core v1.4.1.9
  WR-CBE|Addons v1.4.1.9
  WR-CBE|Logic v1.4.1.9
  YUNoMakeGoodMap v3.0
  McMultipart v1.2.0.345
  ForgeRelocation v0.0.1.4
  MCFrames v1.0
  RelocationFMP v0.0.1.2
  aobd v2.9.1
  IguanaTweaksTConstruct v1.7.10-2.1.6.163
  ForgeMicroblock v1.2.0.345
Server version : 1.7.10 (protocol v5, with Forge).
Translations file loaded.
Version is supported.
Logging in...
Crypto keys & hash generated.
Checking Session...
Forge protocol version : 2
Sending falsified mod list to server...
Accepting server mod list...
Received registry with 8534 entries
Accepting server registries...
Forge server connection complete!
Server was successfully joined.
Type '/quit' to leave the server.

Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.readNextByte(List`1 cache) in C:\Users\ZizzyDizzyMC\Games\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\Protocol18.cs:line 1006
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.readNextBool(List`1 cache) in C:\Users\ZizzyDizzyMC\Games\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\Protocol18.cs:line 820
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.handlePacket(Int32 packetID, List`1 packetData) in C:\Users\ZizzyDizzyMC\Games\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\Protocol18.cs:line 253
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Update() in C:\Users\ZizzyDizzyMC\Games\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\Protocol18.cs:line 96
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater() in C:\Users\ZizzyDizzyMC\Games\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\Protocol18.cs:line 71
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()



```

From reading it looks like it got a lot more than it expected which could be the case.

**Comment by Pokechu22** [comment]
Whoops, that's my fault (and it's not a forge issue; it's a 1.7.10 in general issue).

If you look at [that specific line](https://github.com/ORelio/Minecraft-Console-Client/blob/9fc4215924c3e463ba5b046f581678ef8464b03f/MinecraftClient/Protocol/Handlers/Protocol18.cs#L253), you'll see that it's part of the join game packet.

1.8 added a new field to the Join Game packet, for reducing the amount of debug info.  But that field wasn't in 1.7.10.  Previously, we didn't look at the join game packet, but I added a listener for it in #160 because we needed to know the dimension.  And I just didn't handle that field in 1.7.10.

Submitting a PR to fix this now.

**Comment by ORelio** [comment]
Ah, so that wasn't caused by Forge at all. :sweat_smile:
Please confirm if it worked, @ZizzyDizzyMC :)

**Comment by ORelio** [comment]
Seems like we'll soon be able to move to a stable release, then :)
