### ISSUE TITLE
TerrainAndMovements crashes

### ISSUE THREAD

**Issue by PhotonicMatter** [ORelio/Minecraft-Console-Client#221]
When I enable TerrainAndMovements it crashes, same crash occurs when I run the normal application.

Unhandled Exception: System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
at System.Collections.Generic.List`1.RemoveRange(Int32 index, Int32 count)
at MinecraftClient.Protocol.Handlers.Protocol18Handler.ProcessChunkColumnData(Int32 chunkX, Int32 chunkZ, UInt16 chunkMask, Boolean hasSkyLight, Boolean chunksContinuous, List`1 cache)
at MinecraftClient.Protocol.Handlers.Protocol18Handler.handlePacket(Int32 packetID, List`1 packetData)
at MinecraftClient.Protocol.Handlers.Protocol18Handler.Update()
at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater()
at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()

**Comment by ORelio** [comment]
Seems like a duplicate to #217 , please read & respond to that issue instead :wink:
