### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by itznan** [ORelio/Minecraft-Console-Client#2782]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.20.4

### Console Client Version

MinecraftClient-20240713-273-win-x64.exe

### Expected Behavior

auto eat is not working 

### Actual Behavior

[ERROR] OnUpdateHealth: Got error from MinecraftClient.ChatBots.AutoEat: System.NullReferenceException: Object reference not set to an instance of a    at MinecraftClient.McClient.DispatchBotEvent(Action`1 action, IEnumerable`1 botList)
>

### Steps to Reproduce the bug

1. just turn on autoeat feature
2. 
3. 

### Attach screenshot here (If applicable)

[ERROR] OnUpdateHealth: Got error from MinecraftClient.ChatBots.AutoEat: System.NullReferenceException: Object reference not set to an instance of a    at MinecraftClient.McClient.DispatchBotEvent(Action`1 action, IEnumerable`1 botList)
>

### Device

Laptop

### Operating System

Windows

**Comment by milutinke** [comment]
This should be fixed.
Please try the latest version of the client.
