### ISSUE TITLE
ConsoleClient crashes when kicked while there is already text

### ISSUE THREAD

**Issue by Pokechu22** [ORelio/Minecraft-Console-Client#60]
If kicked from the server or otherwise disconnected while there is already text, the client crashes.  I am using the command-line variation.

Version: `Console Client for MC 1.4.6 to 1.8.1 - v1.8.0`

Stacktrace and text outputted:

> ```
Disconnected by Server :
Kicked from server.                                                            N
ot connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.>Test
Unhandled Except
>>TestSystem.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at MinecraftClient.ConsoleIO.RemoveOneChar()
   at MinecraftClient.ConsoleIO.ClearLineAndBuffer()
   at MinecraftClient.ConsoleIO.Write(String text)
   at MinecraftClient.ConsoleIO.WriteLine(String line)
   at MinecraftClient.McTcpClient.OnConnectionLost(DisconnectReason reason, Stri
ng message)
   at MinecraftClient.Protocol.Handlers.Protocol17Handler.Updater()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

To reproduce, simply connect to a server, start typing something that's at least three letters long (EG `TEST`) but don't send it, switch to the server console, and kick the player you connected as.

**Comment by ORelio** [comment]
Thanks for the detailed crash report with steps to reproduce.
Will take a look at this, it should not be difficult to fix :)

**Comment by ORelio** [comment]
Hello, Seems like it's already fixed in latest versions. Thanks anyway for your report!
