### ISSUE TITLE
After I login it closes

### ISSUE THREAD

**Issue by TranquilizerDart** [ORelio/Minecraft-Console-Client#638]
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.WebRequest.get_PrefixList()
   at System.Net.WebRequest.Create(Uri requestUri, Boolean useUriBase)
   at System.Net.WebRequest.Create(String requestUriString)
   at MinecraftClient.WinAPI.ConsoleIcon.<>c__DisplayClass1_0.<setPlayerIconAsync>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Above is what happens before the window closes.
I have no clue what's going on can anybody help?

**Comment by ORelio** [comment]
Could you please make sure you are using the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)?

**Comment by fisho0** [comment]
I'm using the latest development build on ubuntu 18.04 with mono to connect to a 1.13.2 server.  My player logs in and appears ingame.  in less than a minute, my player signs out ingame.  additionally, the dropped connection is NOT reflected in the Console Client, which acts like nothing is going on indefinitely.

**Comment by fisho0** [comment]
eyoh fisho0 wanted to follow up, here.  I don't know more specifically what the problem is that's making my Console Client to shut down, as described above, but I want to add that I was trying to get it working on a RaspberryPi3+.

I did the same install process on a Ubuntu virtual machine running on "normal" hardware, and it worked just fine.

**Comment by ORelio** [comment]
Hi, sorry about the delay, but after studying the stack trace I think the crash happens when ferching player head icon after login. Try setting `playerheadicon=false` in config to confirm this. Thanks :wink:

**Comment by fisho0** [comment]
I'm using the latest build on 1.14.4 and all is well.  💐💵
