### ISSUE TITLE
Wont work with \K on a regex in match

### ISSUE THREAD

**Issue by BluCobalt** [ORelio/Minecraft-Console-Client#654]
heres the regex in question: https://regex101.com/r/81HcU3/1 
So i tried to make a match that when sent a message containing "000" it would pass it on to members of a group but when i try to launch MCC it gives this error:
`C:\Users\Lukes\OneDrive\Minecraft bot\v2>MinecraftClient.exe
Console Client for MC 1.4.6 to 1.13.2 - v1.13.2 - By ORelio & Contributors
Resolving Server...
Loading Minecraft profiles: launcher_profiles.json
Loading session cache from disk: SessionCache.ini
Loaded session: acc1
Loaded session: acc2
Session data has been successfully loaded from disk.
Performing request to authserver.mojang.com
> POST /validate HTTP/1.1
> Host: authserver.mojang.com
> User-Agent: MCC/1.13.2
> Content-Type: application/json
> Content-Length: 103
> Connection: close
>
> {"accessToken": "censoring", "clientToken": "cause neet" }

< HTTP/1.1 204 No Content
< Connection: close
< Accept-Ranges: bytes
< Date: Fri, 01 Mar 2019 03:37:23 GMT
< Server: Restlet-Framework/2.3.12
< X-Cache: Miss from cloudfront
< Via: 1.1 85ddca57b96353e9e4cd2660cf65d9da.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: HcBWVrV53ZvJrSLM3Ef4Jv6f8GslIgivxHgw-inNm3PhkurIKcDHDA==
<
<
Cached session is still valid for name.
Success. (session ID: 11173f44a7fb4e47a394d26c64551513)
Retrieving Server Info...
Server version : Paper 1.13.2 (protocol v404).
[MCC] [ScriptScheduler] Loading tasks from 'tasks.ini'
[MCC] [ScriptScheduler] Loaded task:
 triggeronfirstlogin = False
 triggeronlogin = True
 triggerontime = False
 triggeroninterval = False
 timevalue =
 timeinterval = 0
 script = hellothere.ini
[MCC] [ScriptScheduler] Cannot find script file: respawn.txt
[MCC] [ScriptScheduler] No valid script for task:
 triggeronfirstlogin = False
 triggeronlogin = True
 triggerontime = False
 triggeroninterval = False
 timevalue =
 timeinterval = 0
 script = respawn.txt

Unhandled Exception: System.ArgumentException: parsing " 0{3}\K(.*?)$" - Unrecognized escape sequence \K.
   at System.Text.RegularExpressions.RegexParser.ScanCharEscape()
   at System.Text.RegularExpressions.RegexParser.ScanBasicBackslash()
   at System.Text.RegularExpressions.RegexParser.ScanBackslash()
   at System.Text.RegularExpressions.RegexParser.ScanRegex()
   at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
   at System.Text.RegularExpressions.Regex..ctor(String pattern)
   at MinecraftClient.ChatBots.AutoRespond.Initialize()
   at MinecraftClient.McTcpClient.BotLoad(ChatBot b, Boolean init)
   at MinecraftClient.McTcpClient.StartClient(String user, String uuid, String sessionID, String server_ip, UInt16 port, Int32 protocolversion, ForgeInfo forgeInfo, Boolean singlecommand, String command)
   at MinecraftClient.McTcpClient..ctor(String username, String uuid, String sessionID, Int32 protocolversion, ForgeInfo forgeInfo, String server_ip, UInt16 port)
   at MinecraftClient.Program.InitializeClient()
   at MinecraftClient.Program.Main(String[] args)

C:\Users\Lukes\OneDrive\Minecraft bot\v2>pause
Press any key to continue . . .`

**Comment by TheSnoozer** [comment]
AFAIK \K is not implemented in C#, so i don't think I can do anything about this.

**Comment by BluCobalt** [comment]
Really? darn thats a shame, thanks for replying though.
