### ISSUE TITLE
When the proxy server is down the client should still try to reconnect and not crash instantly

### ISSUE THREAD

**Issue by CGsama** [ORelio/Minecraft-Console-Client#670]
After setting up a http proxy, when the proxy down, autorelog will crash the program. Everything works fine without a proxy.
> Connection has been lost.
[MCC] [AutoRelog] Waiting 10 seconds before reconnecting...
Restarting Minecraft Console Client...
You chose to run in offline mode.
Using Minecraft version 1.13 (protocol v393)
Connection to proxy host  on port  failed.
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at MinecraftClient.McTcpClient.StartClient(String user, String uuid, String sessionID, String server_ip, UInt16 port, Int32 protocolversion, ForgeInfo forgeInfo, Boolean singlecommand, String command)
   at MinecraftClient.McTcpClient..ctor(String username, String uuid, String sessionID, Int32 protocolversion, ForgeInfo forgeInfo, String server_ip, UInt16 port)
   at MinecraftClient.Program.InitializeClient()
   at MinecraftClient.Program.<>c__DisplayClass11_0.<Restart>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by TheSnoozer** [comment]
What do you expect differently when the proxy is down?

There is literally a message telling you the connection to the proxy failed.

**Comment by CGsama** [comment]
If its server down, it will keep retry to connect, but proxy down will crash. I expect that will keep retry like server down.

**Comment by TheSnoozer** [comment]
I see, thanks for the clarification.

**Comment by ORelio** [comment]
Should be fixed as per latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts), please try it out :wink:

**Comment by CGsama** [comment]
It works fine, not crash anymore. Howerer, my Trend Micro antivirus detect Trojan(TROJ_GEN.R011C0WDP19) in it and delete it, now event can't download it because the web blocker, can you verify it? thx.

**Comment by ORelio** [comment]
See #707 about the trojan issue.
