### ISSUE TITLE
error from build 211

### ISSUE THREAD

**Issue by CGsama** [ORelio/Minecraft-Console-Client#710]
Some thing went wrong when using build 211(CRC32: C48D6B9A), older release(CRC32: 552E484F) works fine. Tried different several different systems.

```
Console Client for MC 1.4.6 to 1.13.2 - v1.13.2 - By ORelio & Contributors
Resolving [HIDDEN]...
Initializing disk session cache using FileSystemWatcher
No sessions could be loaded from disk
You chose to run in offline mode.
Success. (session ID: )
Using Minecraft version 1.11.2 (protocol v316)
Translations file loaded.
Version is supported.
Logging in...
Server is in offline mode.
Server was successfully joined.
Type '/quit' to leave the server.
[HIDDEN] joined the game

Unhandled Exception: System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveRange(Int32 index, Int32 count)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.readData(Int32 offset, List`1 cache)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.readNextInt(List`1 cache)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.handlePacket(Int32 packetID, List`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Update()
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

log from order version:
```
Console Client for MC 1.4.6 to 1.13.2 - v1.13.2 - By ORelio & Contributors
Resolving [HIDDEN]...
No sessions could be loaded from disk
You chose to run in offline mode.
Success. (session ID: )
Using Minecraft version 1.11.2 (protocol v316)
Translations file loaded.
Version is supported.
Logging in...
Server is in offline mode.
Server was successfully joined.
Type '/quit' to leave the server.
[HIDDEN] joined the game
Please, login with the command: /login <password>
[MCC] [AutoRespond] send /login [HIDDEN]
Successful login!
[MCC] [AutoRespond] send /gamemode creative
Welcome [HIDDEN] on [HIDDEN] server

This server uses AuthMeReloaded protection!
I'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error.
```

**Comment by ORelio** [comment]
Thank you for your report, this is likely due to changes introduced while working on #599. Unfortunately, I'm lacking info on which packet is causing the issue. Just pushed a new commit to add more debug info inside the stack trace. Please try it out: [24146265](https://ci.appveyor.com/project/ORelio/minecraft-console-client/builds/24146265).

**Comment by CGsama** [comment]
It's seems like a problem with minecraft version. I'm using 1.13 with viaBackwards dev build. The older version MCC can handle it but newer not.
```
Unhandled Exception: System.IO.InvalidDataException: Failed to process incoming packet of type Respawn. (PacketID: 52, Protocol: 316, LoginPhase: False, InnerException: System.ArgumentException). ---> System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveRange(Int32 index, Int32 count)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.readData(Int32 offset, List`1 cache)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.readNextInt(List`1 cache)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.handlePacket(Int32 packetID, List`1 packetData)
   --- End of inner exception stack trace ---
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.handlePacket(Int32 packetID, List`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Update()
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
server side error is 
`XXX lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.`

**Comment by ORelio** [comment]
Thanks for your report. The bug should be resolved now, please try out [build 214](https://ci.appveyor.com/project/ORelio/minecraft-console-client/builds/24157985/artifacts).

**Comment by CGsama** [comment]
It's working as expected! Thanks!
