### ISSUE TITLE
Current global Palette does not support block Metadata Crash

### ISSUE THREAD

**Issue by searsay** [ORelio/Minecraft-Console-Client#716]
Alright I was having issues with Playerpostionandface so I moved my player off from some glass and onto some grass.  I am now getting this issue when I try to leave the hub.  I tried googling and searching the github.

Running Latest build

Get this error than crash.

>/skyblock
 Sending you to SkyBlock!
>
Unhandled Exception: System.InvalidOperationException: Current global Palette does not support block Metadata
   at MinecraftClient.Mapping.World.GetBlock(Location location)
   at MinecraftClient.Mapping.Movement.IsOnGround(World world, Location location)
   at MinecraftClient.Mapping.Movement.HandleGravity(World world, Location location, Double& motionY)
   at MinecraftClient.McTcpClient.OnUpdate()
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Update()
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by searsay** [comment]
Seems to only be an issue if I try to turn on terrain and movements.  If I relog it doesn't start with it on.  If I switch worlds or /hub it gives me the same error as above.  If I just do /hub or /skyblock without turning on terrainandmovements it goes just fine but then I can not do anything else on the server.  No chat or commands. "You need to move to chat/use commands"

**Comment by ORelio** [comment]
OK, I think I found the reason of this crash. Please try out the latest build.

**Comment by searsay** [comment]
Awesome work! it's good to go.  Thank you for your help and all you do :)
