### ISSUE TITLE
Connection/Network error

### ISSUE THREAD

**Issue by luukoman** [ORelio/Minecraft-Console-Client#888]
Connecting to Minecraft.net...
21:16:02 Performing request to authserver.mojang.com
21:16:02 System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions 13.32.241.68:443
   at MinecraftClient.Protocol.ProtocolHandler.DoHTTPSRequest(List`1 headers, String host, String& result)
   at MinecraftClient.Protocol.ProtocolHandler.DoHTTPSPost(String host, String endpoint, String request, String& result)
   at MinecraftClient.Protocol.ProtocolHandler.GetLogin(String user, String pass, SessionToken& session)
Minecraft Login failed : Network error.

tried reinstalling but it keeps giving me this error.

**Comment by Pokechu22** [comment]
Mojang's authentication servers are currently having issues; see https://twitter.com/MojangStatus/status/1239636222374445057 and https://status.mojang.com/check

**Comment by luukoman** [comment]
got the same issue before they were down
